print('hallo world')
print('what is you name?')
myname = input()
print('it is good to meet you, '+ myname)
print('the length of your name is:')
print(len(myname))
print('what is you age?')
myage = input()
print('you will be ' + str(int(myage) + 1) + ' in a year!')
print('it is good to meet you,  ')
print('the length of your name 15.')
print(len(myname))
print('what is your age')
myage = input()
print('you will be' + str(int(myage) + 1) + ' in a year!')
print(input())
print("welcome to" + input() + "!")
use_name = input(" mohsen;-")